-- ===============================================================================
-- AGL Transport Hub - Microsoft SQL Server (SSMS) DDL Schema Creation Script
-- Target Database: AGL_TransportHub (Microsoft SQL Server / Azure SQL Database)
-- Generated by Antigravity AI - August 2026
-- ===============================================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'AGL_TransportHub')
BEGIN
    CREATE DATABASE [AGL_TransportHub];
END
GO

USE [AGL_TransportHub];
GO

-- 1. Department Table
IF OBJECT_ID(N'dbo.Department', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Department (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        name NVARCHAR(255) NOT NULL,
        code NVARCHAR(50) NOT NULL UNIQUE,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        updatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
    );
END
GO

-- 2. Location Table
IF OBJECT_ID(N'dbo.Location', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Location (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        name NVARCHAR(255) NOT NULL,
        code NVARCHAR(50) NOT NULL UNIQUE,
        address NVARCHAR(500) NOT NULL,
        latitude FLOAT NOT NULL,
        longitude FLOAT NOT NULL,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
    );
END
GO

-- 3. Employee Table
IF OBJECT_ID(N'dbo.Employee', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Employee (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        entraId NVARCHAR(255) NULL UNIQUE,
        email NVARCHAR(255) NOT NULL UNIQUE,
        firstName NVARCHAR(100) NOT NULL,
        lastName NVARCHAR(100) NOT NULL,
        phone NVARCHAR(50) NOT NULL,
        role NVARCHAR(50) NOT NULL DEFAULT 'EMPLOYEE', -- EMPLOYEE, DRIVER, MANAGER, FLEET_ADMIN, SUPER_ADMIN
        departmentId NVARCHAR(36) NOT NULL,
        locationId NVARCHAR(36) NOT NULL,
        managerId NVARCHAR(36) NULL,
        isActive BIT NOT NULL DEFAULT 1,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        updatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_Employee_Department FOREIGN KEY (departmentId) REFERENCES dbo.Department(id),
        CONSTRAINT FK_Employee_Location FOREIGN KEY (locationId) REFERENCES dbo.Location(id),
        CONSTRAINT FK_Employee_Manager FOREIGN KEY (managerId) REFERENCES dbo.Employee(id)
    );
END
GO

-- 4. Driver Table
IF OBJECT_ID(N'dbo.Driver', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Driver (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        employeeId NVARCHAR(36) NOT NULL UNIQUE,
        licenseNumber NVARCHAR(100) NOT NULL,
        licenseCategory NVARCHAR(50) NOT NULL,
        licenseExpiry DATETIME2 NOT NULL,
        status NVARCHAR(50) NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE, ON_TRIP, OFF_DUTY
        CONSTRAINT FK_Driver_Employee FOREIGN KEY (employeeId) REFERENCES dbo.Employee(id) ON DELETE CASCADE
    );
END
GO

-- 5. Vehicle Table
IF OBJECT_ID(N'dbo.Vehicle', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Vehicle (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        registrationNumber NVARCHAR(50) NOT NULL UNIQUE,
        make NVARCHAR(100) NOT NULL,
        model NVARCHAR(100) NOT NULL,
        year INT NOT NULL,
        type NVARCHAR(50) NOT NULL, -- BUS, POOL_CAR, VAN
        capacity INT NOT NULL,
        locationId NVARCHAR(36) NOT NULL,
        status NVARCHAR(50) NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE, IN_USE, UNDER_MAINTENANCE, DECOMMISSIONED
        fuelType NVARCHAR(50) NOT NULL DEFAULT 'Diesel',
        mileage INT NOT NULL DEFAULT 0,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_Vehicle_Location FOREIGN KEY (locationId) REFERENCES dbo.Location(id)
    );
END
GO

-- 6. BusTrip Table
IF OBJECT_ID(N'dbo.BusTrip', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BusTrip (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        vehicleId NVARCHAR(36) NOT NULL,
        driverId NVARCHAR(36) NOT NULL,
        originLocationId NVARCHAR(36) NOT NULL,
        destinationLocationId NVARCHAR(36) NOT NULL,
        departureTime DATETIME2 NOT NULL,
        arrivalTime DATETIME2 NOT NULL,
        totalSeats INT NOT NULL,
        availableSeats INT NOT NULL,
        status NVARCHAR(50) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED
        cutoffHours INT NOT NULL DEFAULT 12,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_BusTrip_Vehicle FOREIGN KEY (vehicleId) REFERENCES dbo.Vehicle(id),
        CONSTRAINT FK_BusTrip_Driver FOREIGN KEY (driverId) REFERENCES dbo.Driver(id),
        CONSTRAINT FK_BusTrip_Origin FOREIGN KEY (originLocationId) REFERENCES dbo.Location(id),
        CONSTRAINT FK_BusTrip_Destination FOREIGN KEY (destinationLocationId) REFERENCES dbo.Location(id)
    );
END
GO

-- 7. BusBooking Table
IF OBJECT_ID(N'dbo.BusBooking', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BusBooking (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        busTripId NVARCHAR(36) NOT NULL,
        employeeId NVARCHAR(36) NOT NULL,
        passengerCount INT NOT NULL DEFAULT 1,
        status NVARCHAR(50) NOT NULL, -- AUTO_APPROVED, PENDING_DRIVER_APPROVAL, APPROVED_BY_DRIVER, REJECTED_BY_DRIVER, CANCELLED
        driverComment NVARCHAR(500) NULL,
        bookedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_BusBooking_BusTrip FOREIGN KEY (busTripId) REFERENCES dbo.BusTrip(id) ON DELETE CASCADE,
        CONSTRAINT FK_BusBooking_Employee FOREIGN KEY (employeeId) REFERENCES dbo.Employee(id)
    );
END
GO

-- 8. PoolVehicleRequest Table
IF OBJECT_ID(N'dbo.PoolVehicleRequest', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PoolVehicleRequest (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        requesterId NVARCHAR(36) NOT NULL,
        approverId NVARCHAR(36) NOT NULL,
        vehicleId NVARCHAR(36) NULL,
        purpose NVARCHAR(1000) NOT NULL,
        startDateTime DATETIME2 NOT NULL,
        endDateTime DATETIME2 NOT NULL,
        status NVARCHAR(50) NOT NULL DEFAULT 'PENDING_MANAGER_APPROVAL', -- PENDING_MANAGER_APPROVAL, APPROVED, REJECTED, CHECKED_OUT, RETURNED, CANCELLED
        rejectionReason NVARCHAR(500) NULL,
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_PoolRequest_Requester FOREIGN KEY (requesterId) REFERENCES dbo.Employee(id),
        CONSTRAINT FK_PoolRequest_Approver FOREIGN KEY (approverId) REFERENCES dbo.Employee(id),
        CONSTRAINT FK_PoolRequest_Vehicle FOREIGN KEY (vehicleId) REFERENCES dbo.Vehicle(id)
    );
END
GO

-- 9. VehicleInspection Table
IF OBJECT_ID(N'dbo.VehicleInspection', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VehicleInspection (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        poolVehicleRequestId NVARCHAR(36) NOT NULL UNIQUE,
        vehicleId NVARCHAR(36) NOT NULL,
        inspectorId NVARCHAR(36) NOT NULL,
        inspectionType NVARCHAR(50) NOT NULL DEFAULT 'POST_RETURN', -- PRE_TRIP, POST_RETURN
        odometerReading INT NOT NULL,
        fuelLevelPercent INT NOT NULL,
        cleanlinessStatus NVARCHAR(100) NOT NULL,
        damageNotes NVARCHAR(1000) NULL,
        photoUrls NVARCHAR(MAX) NOT NULL DEFAULT '[]', -- JSON array of image URLs
        passStatus NVARCHAR(50) NOT NULL DEFAULT 'PASSED', -- PASSED, FLAGGED_NEEDS_SERVICE
        inspectedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_Inspection_PoolRequest FOREIGN KEY (poolVehicleRequestId) REFERENCES dbo.PoolVehicleRequest(id) ON DELETE CASCADE,
        CONSTRAINT FK_Inspection_Vehicle FOREIGN KEY (vehicleId) REFERENCES dbo.Vehicle(id),
        CONSTRAINT FK_Inspection_Inspector FOREIGN KEY (inspectorId) REFERENCES dbo.Employee(id)
    );
END
GO

-- 10. ApprovalTask Table
IF OBJECT_ID(N'dbo.ApprovalTask', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ApprovalTask (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        requestType NVARCHAR(100) NOT NULL, -- BUS_LATE_BOOKING, POOL_VEHICLE_REQUEST
        referenceId NVARCHAR(36) NOT NULL,
        requesterId NVARCHAR(36) NOT NULL,
        assigneeId NVARCHAR(36) NOT NULL,
        status NVARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
        createdAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        actionedAt DATETIME2 NULL,
        CONSTRAINT FK_ApprovalTask_Requester FOREIGN KEY (requesterId) REFERENCES dbo.Employee(id),
        CONSTRAINT FK_ApprovalTask_Assignee FOREIGN KEY (assigneeId) REFERENCES dbo.Employee(id)
    );
END
GO

-- 11. AuditEvent Table
IF OBJECT_ID(N'dbo.AuditEvent', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AuditEvent (
        id NVARCHAR(36) NOT NULL PRIMARY KEY DEFAULT NEWID(),
        performerId NVARCHAR(36) NOT NULL,
        action NVARCHAR(255) NOT NULL,
        entityType NVARCHAR(100) NOT NULL,
        entityId NVARCHAR(36) NOT NULL,
        metadata NVARCHAR(MAX) NULL, -- JSON string
        ipAddress NVARCHAR(100) NULL,
        userAgent NVARCHAR(500) NULL,
        timestamp DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT FK_AuditEvent_Performer FOREIGN KEY (performerId) REFERENCES dbo.Employee(id)
    );
END
GO
